services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: herbbossng
    ports:
      - '5432:5432'
    volumes:
      - herbbossng_db:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI

volumes:
  herbbossng_db:
