import type { PermissionAction, PermissionModule } from '@/types/database'

export const moduleOrder: PermissionModule[] = [
  'dashboard',
  'orders',
  'operations',
  'fulfillment',
  'waybills',
  'delivery_partners',
  'tasks',
  'settlement',
  'products',
  'categories',
  'landing_pages',
  'customers',
  'inventory',
  'finance',
  'analytics',
  'reports',
  'affiliates',
  'campaigns',
  'commissions',
  'wallets',
  'withdrawals',
  'ad_costs',
  'affiliate_reports',
  'marketing',
  'staff',
  'roles_permissions',
  'notifications',
  'audit_logs',
  'brands',
  'workspace',
  'settings',
  'support',
  'assignment_rules',
  'approval_rules',
  'automation',
]

export const moduleLabels: Record<PermissionModule, string> = {
  dashboard: 'Dashboard',
  orders: 'Orders',
  operations: 'Operations',
  fulfillment: 'Fulfillment',
  waybills: 'Waybills',
  delivery_partners: 'Delivery Partners',
  tasks: 'Follow-up Tasks',
  settlement: 'COD Settlement',
  products: 'Products',
  categories: 'Categories',
  landing_pages: 'Landing Pages',
  customers: 'Customers',
  inventory: 'Inventory',
  finance: 'Finance',
  analytics: 'Analytics',
  reports: 'Reports',
  affiliates: 'Affiliates',
  campaigns: 'Campaigns',
  commissions: 'Commissions',
  wallets: 'Wallets',
  withdrawals: 'Withdrawals',
  ad_costs: 'Ad Costs',
  affiliate_reports: 'Affiliate Reports',
  marketing: 'Marketing',
  staff: 'Staff',
  roles_permissions: 'Roles & Permissions',
  notifications: 'Notifications',
  audit_logs: 'Audit Logs',
  brands: 'Brands',
  workspace: 'Workspace',
  settings: 'Settings',
  support: 'Support',
  assignment_rules: 'Assignment Rules',
  approval_rules: 'Approval Rules',
  automation: 'Automation',
}

export const actionOrder: PermissionAction[] = ['view', 'create', 'update', 'delete', 'assign', 'approve', 'export', 'import', 'manage']

export const actionLabels: Record<PermissionAction, string> = {
  view: 'View',
  create: 'Create',
  update: 'Update',
  delete: 'Delete',
  assign: 'Assign',
  approve: 'Approve',
  export: 'Export',
  import: 'Import',
  manage: 'Manage',
}
