-- ============================================================
-- GOLDEN COMMERCE OS — Omnichannel Order Ingestion, Foundation
-- (0053): Shopify, WooCommerce, and Google Sheets as external order
-- sources feeding the SAME order engine every other channel already
-- uses (landing pages, manual entry, affiliates). No parallel order/
-- customer/inventory system is created here — every external order
-- ends up as one ordinary row in public.orders, created the same way
-- create_order()/create_public_order() already do: canonical-phone
-- customer resolution, live product pricing, adjust_inventory_internal()
-- for stock, and the existing emit_orders_created trigger, which means
-- automation rules, staff notifications, and the Integration Health
-- "Automation Retry Queue" all work on an ingested order with ZERO
-- additional wiring (see 0028's emit_order_created_event()).
--
-- Audited before writing a single line here (see the accompanying
-- engineering report): there is no existing Shopify/WooCommerce code
-- anywhere in this repo, no existing Google Sheets integration, no
-- external-order-id concept on orders, and the workspace->brand
-- hierarchy has no separate "market" entity — connections here are
-- brand-scoped, exactly like brand_communication_secrets/
-- brand_tracking_secrets (0031/0032), which this migration copies the
-- secret-storage discipline from verbatim: RLS enabled with NO client
-- policies, reachable only through SECURITY DEFINER RPCs, and a secret
-- value is never once returned to the browser.
--
-- Shape of this migration:
--   PART A — orders: new source values + external-id columns
--   PART B — permissions: order_ingestion.view / .manage
--   PART C — external_connections (brand-scoped provider secrets)
--   PART D — external_order_ingestion_log (idempotency + retry queue)
--   PART E — external_product_mappings (deterministic item resolution)
--   PART F — the shared ingestion pipeline (ingest_external_order /
--            process_external_order_ingestion) every provider calls
--   PART G — staff-facing RPCs (connect/disconnect/list/retry/map)
--   PART H — service-role-only RPCs for the ingestion Edge Functions
--   PART I — realtime
-- ============================================================


-- ----------------------------------------------------------------
-- PART A — orders: widen the source vocabulary, add external
-- reference columns. idempotency_key already protects against a
-- literal retry of the same submission; external_order_id is a
-- DIFFERENT concept — it is how GCOS recognizes "I have already
-- ingested Shopify order #1042 for this connection", independent of
-- anything GCOS itself generated.
-- ----------------------------------------------------------------
alter table public.orders
  add column if not exists external_source text,
  add column if not exists external_connection_id uuid,
  add column if not exists external_order_id text,
  add column if not exists external_order_number text;

alter table public.orders drop constraint orders_source_check;
alter table public.orders add constraint orders_source_check
  check (source in (
    'website', 'whatsapp', 'phone', 'facebook', 'instagram', 'tiktok',
    'walk_in', 'manual', 'affiliate', 'landing_page',
    'shopify', 'woocommerce', 'google_sheets', 'other'
  ));

create unique index orders_external_source_idx
  on public.orders (workspace_id, brand_id, external_source, external_order_id)
  where external_order_id is not null;

comment on column public.orders.external_source is
  'Set only for orders created by ingest_external_order() (''shopify''/''woocommerce''/''google_sheets''); null for every other channel. Mirrors orders.source but kept as its own column so a future rename of source''s vocabulary can never silently break ingestion idempotency.';
comment on column public.orders.external_order_id is
  'The foreign system''s own order id/number (e.g. a Shopify numeric order id, a WooCommerce order id, a Google Sheets row key) — never generated by GCOS. Unique per (workspace_id, brand_id, external_source, external_order_id); the actual dedup authority is external_order_ingestion_log''s unique (connection_id, external_order_id), enforced before this row ever gets inserted.';


-- ----------------------------------------------------------------
-- PART B — permissions. No existing per-provider permission exists
-- anywhere in GCOS (communications.* covers email+sms+whatsapp
-- together, landing_pages.tracking.* covers meta+tiktok together) —
-- order_ingestion.* follows that exact granularity: one pair covering
-- all three providers, not nine provider-specific permissions.
-- ----------------------------------------------------------------
insert into public.permissions (module, action, slug, category, description) values
  ('order_ingestion', 'view', 'order_ingestion.view', 'Order Ingestion', 'View connected order sources (Shopify/WooCommerce/Google Sheets), sync history, and orders awaiting review'),
  ('order_ingestion', 'manage', 'order_ingestion.manage', 'Order Ingestion', 'Connect/disconnect external order sources, map unresolved products, and retry failed or needs-review ingested orders')
on conflict (slug) do nothing;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id from public.roles r cross join public.permissions p
where r.workspace_id is null and r.slug in ('owner', 'admin') and p.module = 'order_ingestion'
on conflict do nothing;

-- Same "view" reach as integrations.view: managers/marketing/viewers
-- can see connection health and sync history; only owner/admin can
-- connect a store or touch product mappings.
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id from public.roles r cross join public.permissions p
where r.workspace_id is null and r.slug in ('manager', 'marketing', 'viewer') and p.module = 'order_ingestion' and p.action = 'view'
on conflict do nothing;


-- ----------------------------------------------------------------
-- PART C — external_connections: one row per brand+provider. Exact
-- brand_communication_secrets discipline — RLS enabled, ZERO client
-- policies, unreachable from the frontend except through the RPCs in
-- PART G, and never through a raw select.
-- ----------------------------------------------------------------
create table public.external_connections (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  brand_id uuid not null references public.brands (id) on delete cascade,
  provider text not null check (provider in ('shopify', 'woocommerce', 'google_sheets')),

  status text not null default 'disconnected' check (status in ('disconnected', 'connected', 'error')),
  last_error text,
  last_sync_at timestamptz,
  -- Free-form per-provider incremental-sync checkpoint (WooCommerce:
  -- {"after": "<ISO8601>"}; Google Sheets: {"last_row": 42}). Shopify
  -- is webhook-push and never needs one.
  sync_cursor jsonb not null default '{}'::jsonb,

  -- Shopify: a custom/private app's Admin API access token plus the
  -- app's own API secret (used only to verify X-Shopify-Hmac-Sha256 on
  -- inbound webhooks — never sent anywhere).
  shopify_shop_domain text,
  shopify_access_token text,
  shopify_api_secret text,

  -- WooCommerce: REST API v3 key pair (Basic Auth over HTTPS).
  woocommerce_store_url text,
  woocommerce_consumer_key text,
  woocommerce_consumer_secret text,

  -- Google Sheets: real OAuth (authorization-code flow), never a
  -- pasted access token — access tokens expire in ~1 hour, so the
  -- refresh_token is the credential that actually matters here.
  google_refresh_token text,
  google_access_token text,
  google_access_token_expires_at timestamptz,
  google_spreadsheet_id text,
  google_sheet_name text,
  google_column_mapping jsonb not null default '{}'::jsonb,
  google_header_row boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id),
  updated_by uuid references auth.users (id),
  unique (brand_id, provider)
);

comment on table public.external_connections is
  'One row per brand+provider external order source. RLS enabled with NO policies for any client role — the exact brand_communication_secrets (0032) discipline: reachable only via upsert_external_connection()/disconnect_external_connection() (write, secrets never echoed back), get_external_connections() (read, secrets omitted entirely), and the service-role-only resolvers in PART H used by the ingestion Edge Functions. Never select this table directly from the frontend.';

alter table public.external_connections enable row level security;

create trigger set_external_connections_updated_at
  before update on public.external_connections
  for each row execute function public.set_updated_at();

alter table public.orders
  add constraint orders_external_connection_id_fkey foreign key (external_connection_id) references public.external_connections (id) on delete set null;


-- ----------------------------------------------------------------
-- PART D — external_order_ingestion_log: the idempotency ledger,
-- audit trail, AND retry queue for every external order ingestion
-- attempt in one table (deliberately not split three ways — a
-- provider webhook re-delivery, a staff manual retry, and a scheduled
-- backoff retry are all just another call into the same pipeline
-- against the same row). input_* columns capture exactly what the
-- caller supplied so a retry never needs to re-fetch anything from
-- the provider; raw_payload is kept purely for audit/debugging and is
-- never re-parsed by the pipeline itself.
-- ----------------------------------------------------------------
create table public.external_order_ingestion_log (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  brand_id uuid not null references public.brands (id) on delete cascade,
  connection_id uuid not null references public.external_connections (id) on delete cascade,
  provider text not null check (provider in ('shopify', 'woocommerce', 'google_sheets')),

  external_order_id text not null,
  external_order_number text,

  status text not null default 'pending' check (status in (
    'pending', 'processing', 'ingested', 'needs_review', 'failed', 'permanently_failed'
  )),
  order_id uuid references public.orders (id) on delete set null,

  input_customer jsonb not null default '{}'::jsonb,
  input_items jsonb not null default '[]'::jsonb,
  input_shipping_fee numeric(14, 2) not null default 0,
  input_discount_amount numeric(14, 2) not null default 0,
  input_currency_code text,
  input_source_detail text,
  raw_payload jsonb not null default '{}'::jsonb,

  normalized_items jsonb,
  unresolved_items jsonb,
  error_message text,

  attempts integer not null default 0,
  max_attempts integer not null default 5,
  next_retry_at timestamptz,
  claimed_at timestamptz,
  claimed_by text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.external_order_ingestion_log is
  'One row per (connection_id, external_order_id), forever — a re-delivered Shopify webhook, a re-fetched WooCommerce page, or a re-read Google Sheets row all resolve to this SAME row, never a duplicate order. needs_review rows hold at least one line item that could not be matched to an internal product (see PART F) and carry NO order_id — GCOS never guesses a product match. failed/permanently_failed rows follow the identical exponential-backoff discipline as communication_log/tracking_dispatch_log (0032).';

create unique index external_order_ingestion_log_idempotency_idx
  on public.external_order_ingestion_log (connection_id, external_order_id);
create index external_order_ingestion_log_workspace_idx on public.external_order_ingestion_log (workspace_id, created_at desc);
create index external_order_ingestion_log_retry_idx on public.external_order_ingestion_log (status, next_retry_at) where status = 'failed';
create index external_order_ingestion_log_processing_idx on public.external_order_ingestion_log (claimed_at) where status = 'processing';
create index external_order_ingestion_log_review_idx on public.external_order_ingestion_log (workspace_id, status) where status = 'needs_review';

alter table public.external_order_ingestion_log enable row level security;

create trigger set_external_order_ingestion_log_updated_at
  before update on public.external_order_ingestion_log
  for each row execute function public.set_updated_at();

-- Select-only for staff — same dual-permission shape as
-- list_communication_log (0032): a workspace's general integrations
-- viewer can see this without needing the narrower order_ingestion.view.
create policy "select_external_order_ingestion_log" on public.external_order_ingestion_log
  for select to authenticated
  using (
    workspace_id in (select public.user_workspace_ids())
    and (public.user_has_permission(workspace_id, 'order_ingestion.view') or public.user_has_permission(workspace_id, 'integrations.view'))
  );


-- ----------------------------------------------------------------
-- PART E — external_product_mappings: explicit external-line-item ->
-- internal product overrides. Checked FIRST by the pipeline, before
-- a SKU match against products.sku — the deterministic, never-guess
-- resolution order the whole feature is built around.
-- ----------------------------------------------------------------
create table public.external_product_mappings (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  brand_id uuid not null references public.brands (id) on delete cascade,
  connection_id uuid not null references public.external_connections (id) on delete cascade,
  external_product_id text,
  external_variant_id text,
  external_sku text,
  product_id uuid not null references public.products (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id),
  unique (connection_id, external_product_id, external_variant_id)
);

comment on table public.external_product_mappings is
  'Explicit external-line-item -> internal product overrides, resolved FIRST (before a products.sku match) by process_external_order_ingestion(): (1) this table, keyed on (connection_id, external_product_id, external_variant_id); (2) an exact products.sku match on the same brand; (3) unresolved, routing the whole order to needs_review. Created via upsert_external_product_mapping(), typically from the Failed Order Review screen.';

create index external_product_mappings_sku_idx on public.external_product_mappings (connection_id, external_sku) where external_sku is not null;

alter table public.external_product_mappings enable row level security;

create trigger set_external_product_mappings_updated_at
  before update on public.external_product_mappings
  for each row execute function public.set_updated_at();

create policy "select_external_product_mappings" on public.external_product_mappings
  for select to authenticated
  using (
    workspace_id in (select public.user_workspace_ids())
    and (public.user_has_permission(workspace_id, 'order_ingestion.view') or public.user_has_permission(workspace_id, 'integrations.view'))
  );


-- ================================================================
-- PART F — the shared ingestion pipeline. EVERY provider (Shopify
-- webhook, WooCommerce sync worker, Google Sheets sync worker, and
-- any future source) funnels through ingest_external_order() with
-- one normalized shape:
--   p_customer: {name, phone, email, country_code, state, city,
--                address, address_2, postal_code}
--   p_items:    [{external_product_id, external_variant_id,
--                 external_sku, name, quantity, unit_price}, ...]
-- Provider-specific parsing (Shopify's nested line_items, WooCommerce's
-- billing/shipping split, a Sheets row's mapped columns) all happens
-- in the calling Edge Function — this function never knows or cares
-- which provider produced the shape.
-- ================================================================
create or replace function public.ingest_external_order(
  p_connection_id uuid,
  p_external_order_id text,
  p_external_order_number text,
  p_customer jsonb,
  p_items jsonb,
  p_shipping_fee numeric default 0,
  p_discount_amount numeric default 0,
  p_currency_code text default null,
  p_source_detail text default null,
  p_raw_payload jsonb default '{}'::jsonb
)
returns public.external_order_ingestion_log
language plpgsql
security definer
set search_path = public
as $$
declare
  v_conn public.external_connections%rowtype;
  v_log public.external_order_ingestion_log%rowtype;
begin
  if coalesce(trim(p_external_order_id), '') = '' then
    raise exception 'external_order_id is required';
  end if;

  select * into v_conn from public.external_connections where id = p_connection_id;
  if not found then
    raise exception 'Unknown connection %', p_connection_id;
  end if;

  -- Idempotency: exactly one row per (connection_id, external_order_id)
  -- ever gets created. A brand-new order takes this branch.
  insert into public.external_order_ingestion_log (
    workspace_id, brand_id, connection_id, provider, external_order_id, external_order_number,
    status, input_customer, input_items, input_shipping_fee, input_discount_amount,
    input_currency_code, input_source_detail, raw_payload
  ) values (
    v_conn.workspace_id, v_conn.brand_id, p_connection_id, v_conn.provider, trim(p_external_order_id), nullif(p_external_order_number, ''),
    'pending', coalesce(p_customer, '{}'::jsonb), coalesce(p_items, '[]'::jsonb), coalesce(p_shipping_fee, 0), coalesce(p_discount_amount, 0),
    p_currency_code, p_source_detail, coalesce(p_raw_payload, '{}'::jsonb)
  )
  on conflict (connection_id, external_order_id) do nothing
  returning * into v_log;

  if v_log.id is not null then
    return public.process_external_order_ingestion(v_log.id);
  end if;

  -- Already seen this external_order_id before — decide whether THIS
  -- call should reprocess the existing row.
  select * into v_log from public.external_order_ingestion_log
    where connection_id = p_connection_id and external_order_id = trim(p_external_order_id);

  if v_log.status = 'processing' and v_log.claimed_at < now() - interval '10 minutes' then
    -- A prior attempt crashed mid-transaction (or the Edge Function
    -- itself died) without ever reaching a terminal status — same
    -- 10-minute reclaim window as communication_log/tracking_dispatch_log.
    return public.process_external_order_ingestion(v_log.id);
  end if;

  if v_log.status = 'failed' and (v_log.next_retry_at is null or v_log.next_retry_at <= now()) then
    -- A repeat delivery of a previously-failed webhook (Shopify retries
    -- failed webhooks automatically) or a re-fetch of a row that failed
    -- last sync is a legitimate, free retry opportunity — take it,
    -- respecting the same backoff window a scheduled retry would.
    return public.process_external_order_ingestion(v_log.id);
  end if;

  -- ingested / needs_review / a fresh processing row / a failed row
  -- still inside its backoff window: never reprocessed by a repeat
  -- delivery. needs_review in particular must wait for a human
  -- (retry_external_order_ingestion), never silently retried with the
  -- same unresolved items.
  return v_log;
end;
$$;

revoke execute on function public.ingest_external_order(uuid, text, text, jsonb, jsonb, numeric, numeric, text, text, jsonb) from public, anon, authenticated;

comment on function public.ingest_external_order(uuid, text, text, jsonb, jsonb, numeric, numeric, text, text, jsonb) is
  'The single entry point every provider adapter calls (Shopify webhook, WooCommerce sync worker, Google Sheets sync worker). Never callable by anon/authenticated — only a service-role Edge Function that has already verified the request''s legitimacy (Shopify HMAC, WooCommerce Basic Auth, a valid Google access token) may call this. Idempotent on (connection_id, external_order_id) forever; see process_external_order_ingestion() for the actual customer/product/order pipeline.';


create or replace function public.process_external_order_ingestion(p_log_id uuid)
returns public.external_order_ingestion_log
language plpgsql
security definer
set search_path = public
as $$
declare
  v_log public.external_order_ingestion_log%rowtype;
  v_conn public.external_connections%rowtype;
  v_workspace_currency text;
  v_workspace_country text;
  v_dial_code text;
  v_canonical_phone text;
  v_first_name text;
  v_last_name text;
  v_customer_name text;
  v_customer_id uuid;
  v_is_repeat boolean;
  v_item jsonb;
  v_resolved_product_id uuid;
  v_resolved_name text;
  v_resolved_sku text;
  v_resolved_cost numeric;
  v_quantity integer;
  v_unit_price numeric;
  v_unresolved jsonb := '[]'::jsonb;
  v_normalized_items jsonb := '[]'::jsonb;
  v_subtotal numeric := 0;
  v_cost numeric := 0;
  v_total numeric;
  v_currency text;
  v_order_number text;
  v_order public.orders%rowtype;
  v_dup_order_number text;
  v_dup_created_at timestamptz;
  v_possible_duplicate boolean := false;
  v_next_attempts integer;
begin
  select * into v_log from public.external_order_ingestion_log where id = p_log_id for update;
  if not found then
    raise exception 'Ingestion log row % not found', p_log_id;
  end if;

  select * into v_conn from public.external_connections where id = v_log.connection_id;
  if not found then
    raise exception 'Connection % no longer exists', v_log.connection_id;
  end if;

  v_next_attempts := v_log.attempts + 1;
  update public.external_order_ingestion_log
    set status = 'processing', attempts = v_next_attempts, claimed_at = now(), claimed_by = 'inline', updated_at = now()
    where id = p_log_id;

  begin
    select currency_code, country_code into v_workspace_currency, v_workspace_country
      from public.workspaces where id = v_conn.workspace_id;

    select dial_code into v_dial_code from public.countries
      where code = coalesce(nullif(v_log.input_customer ->> 'country_code', ''), v_workspace_country);

    v_canonical_phone := public.normalize_phone(v_log.input_customer ->> 'phone', v_dial_code);
    if v_canonical_phone is null then
      raise exception 'A valid customer phone number is required to ingest an order';
    end if;

    v_customer_name := trim(nullif(v_log.input_customer ->> 'name', ''));
    if v_customer_name is null or v_customer_name = '' then
      v_customer_name := 'Customer ' || v_log.external_order_number;
    end if;
    v_first_name := split_part(v_customer_name, ' ', 1);
    v_last_name := nullif(trim(substring(v_customer_name from length(v_first_name) + 1)), '');

    select id into v_customer_id from public.customers
      where workspace_id = v_conn.workspace_id and brand_id = v_conn.brand_id
        and canonical_phone = v_canonical_phone and deleted_at is null;

    if not found then
      insert into public.customers (
        workspace_id, brand_id, first_name, last_name, full_name, phone, canonical_phone,
        email, country_code, state, city, address, address_2, postal_code, acquisition_source
      ) values (
        v_conn.workspace_id, v_conn.brand_id, v_first_name, v_last_name, v_customer_name,
        v_log.input_customer ->> 'phone', v_canonical_phone,
        nullif(v_log.input_customer ->> 'email', ''), coalesce(nullif(v_log.input_customer ->> 'country_code', ''), v_workspace_country),
        v_log.input_customer ->> 'state', v_log.input_customer ->> 'city', coalesce(v_log.input_customer ->> 'address', ''),
        v_log.input_customer ->> 'address_2', v_log.input_customer ->> 'postal_code', v_conn.provider
      )
      on conflict (workspace_id, brand_id, canonical_phone) where deleted_at is null
        do update set updated_at = now()
      returning id into v_customer_id;
    end if;

    select exists(
      select 1 from public.orders where customer_id = v_customer_id and deleted_at is null
    ) into v_is_repeat;

    -- Same possible-duplicate definition as create_order()/create_public_order()
    -- (0052): another non-cancelled/non-returned order from this same
    -- customer in the last 24 hours.
    select o.order_number, o.created_at into v_dup_order_number, v_dup_created_at
      from public.orders o
      where o.customer_id = v_customer_id and o.deleted_at is null
        and o.status not in ('CANCELLED', 'RETURNED')
        and o.created_at > now() - interval '24 hours'
      order by o.created_at desc
      limit 1;
    v_possible_duplicate := found;

    -- Deterministic product resolution — never guess. A single
    -- unresolved item routes the WHOLE order to needs_review, since a
    -- partially-created order would misstate its own total.
    v_unresolved := '[]'::jsonb;
    v_normalized_items := '[]'::jsonb;
    v_subtotal := 0;
    v_cost := 0;

    for v_item in select * from jsonb_array_elements(coalesce(v_log.input_items, '[]'::jsonb))
    loop
      v_quantity := greatest(coalesce((v_item ->> 'quantity')::integer, 1), 1);
      v_unit_price := coalesce((v_item ->> 'unit_price')::numeric, 0);
      v_resolved_product_id := null;

      select product_id into v_resolved_product_id from public.external_product_mappings
        where connection_id = v_log.connection_id
          and coalesce(external_product_id, '') = coalesce(v_item ->> 'external_product_id', '')
          and coalesce(external_variant_id, '') = coalesce(v_item ->> 'external_variant_id', '');

      if v_resolved_product_id is null and coalesce(v_item ->> 'external_sku', '') <> '' then
        select id into v_resolved_product_id from public.products
          where brand_id = v_conn.brand_id and sku = (v_item ->> 'external_sku') and deleted_at is null;
      end if;

      if v_resolved_product_id is null then
        v_unresolved := v_unresolved || jsonb_build_array(v_item);
      else
        select name, sku, cost_price into v_resolved_name, v_resolved_sku, v_resolved_cost
          from public.products where id = v_resolved_product_id;
        v_normalized_items := v_normalized_items || jsonb_build_array(jsonb_build_object(
          'product_id', v_resolved_product_id, 'name', v_resolved_name, 'sku', v_resolved_sku,
          'quantity', v_quantity, 'unit_price', v_unit_price, 'unit_cost', coalesce(v_resolved_cost, 0),
          'external_product_id', v_item ->> 'external_product_id', 'external_sku', v_item ->> 'external_sku'
        ));
        v_subtotal := v_subtotal + v_unit_price * v_quantity;
        v_cost := v_cost + coalesce(v_resolved_cost, 0) * v_quantity;
      end if;
    end loop;

    if jsonb_array_length(v_unresolved) > 0 then
      update public.external_order_ingestion_log
        set status = 'needs_review', unresolved_items = v_unresolved, normalized_items = v_normalized_items,
            error_message = 'unresolved_items: ' || jsonb_array_length(v_unresolved) || ' line item(s) could not be matched to a product',
            next_retry_at = null, updated_at = now()
        where id = p_log_id
        returning * into v_log;
      return v_log;
    end if;

    if jsonb_array_length(v_normalized_items) = 0 then
      raise exception 'Order has no items to ingest';
    end if;

    v_currency := coalesce(nullif(v_log.input_currency_code, ''), v_workspace_currency, 'USD');
    v_total := v_subtotal + v_log.input_shipping_fee - v_log.input_discount_amount;

    v_order_number := public.generate_order_number(v_conn.workspace_id);

    insert into public.orders (
      workspace_id, brand_id, order_number, source, status, priority,
      customer_id, customer_name, customer_phone, customer_email, customer_country_code,
      customer_state, customer_city, customer_address, customer_address_2, customer_postal_code,
      currency_code, subtotal, shipping_fee, discount_amount, total_amount, cost_amount, expected_profit,
      source_detail, is_repeat_customer,
      external_source, external_connection_id, external_order_id, external_order_number,
      metadata
    ) values (
      v_conn.workspace_id, v_conn.brand_id, v_order_number, v_conn.provider, 'NEW', 'normal',
      v_customer_id, v_customer_name, v_log.input_customer ->> 'phone', nullif(v_log.input_customer ->> 'email', ''),
      coalesce(nullif(v_log.input_customer ->> 'country_code', ''), v_workspace_country),
      v_log.input_customer ->> 'state', v_log.input_customer ->> 'city',
      coalesce(v_log.input_customer ->> 'address', ''), v_log.input_customer ->> 'address_2', v_log.input_customer ->> 'postal_code',
      v_currency, v_subtotal, v_log.input_shipping_fee, v_log.input_discount_amount, v_total, v_cost, v_subtotal - v_cost,
      coalesce(v_log.input_source_detail, initcap(replace(v_conn.provider, '_', ' '))), v_is_repeat,
      v_conn.provider, v_conn.id, v_log.external_order_id, v_log.external_order_number,
      jsonb_build_object(
        'item_summary', (select string_agg((i ->> 'name') || ' x' || (i ->> 'quantity'), ', ') from jsonb_array_elements(v_normalized_items) i),
        'item_quantity', (select sum((i ->> 'quantity')::integer) from jsonb_array_elements(v_normalized_items) i),
        'possible_duplicate', v_possible_duplicate,
        'duplicate_of_order_number', v_dup_order_number,
        'duplicate_minutes_ago', case when v_possible_duplicate then round(extract(epoch from (now() - v_dup_created_at)) / 60) else null end
      )
    )
    returning * into v_order;

    for v_item in select * from jsonb_array_elements(v_normalized_items)
    loop
      insert into public.order_items (
        order_id, workspace_id, brand_id, product_id, product_name, sku, quantity, unit_price, unit_cost, total_amount
      ) values (
        v_order.id, v_conn.workspace_id, v_conn.brand_id, (v_item ->> 'product_id')::uuid, v_item ->> 'name', v_item ->> 'sku',
        (v_item ->> 'quantity')::integer, (v_item ->> 'unit_price')::numeric, (v_item ->> 'unit_cost')::numeric,
        (v_item ->> 'unit_price')::numeric * (v_item ->> 'quantity')::integer
      );

      if (select track_inventory from public.products where id = (v_item ->> 'product_id')::uuid) then
        -- adjust_inventory_internal(), not adjust_inventory(): this
        -- pipeline runs SECURITY DEFINER with no auth.uid() at all
        -- (called from a service-role Edge Function, not a staff
        -- session) — the exact same reason create_public_order() calls
        -- the internal core directly (0031, PART E1).
        perform public.adjust_inventory_internal(
          (v_item ->> 'product_id')::uuid, 'RESERVED', (v_item ->> 'quantity')::integer,
          'Order ' || v_order_number || ' created (' || v_conn.provider || ')', 'order', v_order.id
        );
      end if;
    end loop;

    update public.external_order_ingestion_log
      set status = 'ingested', order_id = v_order.id, normalized_items = v_normalized_items, unresolved_items = null,
          error_message = null, next_retry_at = null, updated_at = now()
      where id = p_log_id
      returning * into v_log;

    update public.external_connections
      set status = 'connected', last_error = null, last_sync_at = now()
      where id = v_conn.id;

  exception when others then
    update public.external_order_ingestion_log
      set status = case when v_next_attempts >= max_attempts then 'permanently_failed' else 'failed' end,
          error_message = left(sqlerrm, 2000),
          next_retry_at = case when v_next_attempts >= max_attempts then null
            else now() + (least(power(2, v_next_attempts)::int * 30, 3600) || ' seconds')::interval end,
          updated_at = now()
      where id = p_log_id
      returning * into v_log;

    update public.external_connections
      set status = 'error', last_error = left(sqlerrm, 2000)
      where id = v_conn.id;
  end;

  return v_log;
end;
$$;

revoke execute on function public.process_external_order_ingestion(uuid) from public, anon, authenticated;

comment on function public.process_external_order_ingestion(uuid) is
  'The actual customer/product/order pipeline, operating entirely off a log row''s own input_* columns (never re-fetches anything from the provider). Called by ingest_external_order() for a first attempt, by retry_external_order_ingestion() for a staff-triggered retry, and by the retry-external-ingestion Edge Function (via claim_external_ingestion_retry_batch()) for a scheduled backoff retry — all three are the identical code path. Not callable by anon/authenticated.';


-- ================================================================
-- PART G — staff-facing RPCs.
-- ================================================================
create or replace function public.upsert_external_connection(
  p_brand_id uuid,
  p_provider text,
  p_shopify_shop_domain text default null,
  p_shopify_access_token text default null,
  p_shopify_api_secret text default null,
  p_woocommerce_store_url text default null,
  p_woocommerce_consumer_key text default null,
  p_woocommerce_consumer_secret text default null,
  p_google_spreadsheet_id text default null,
  p_google_sheet_name text default null,
  p_google_column_mapping jsonb default null,
  p_google_header_row boolean default null
)
returns public.external_connections
language plpgsql
security definer
set search_path = public
as $$
declare
  v_brand public.brands%rowtype;
  v_row public.external_connections%rowtype;
begin
  if p_provider not in ('shopify', 'woocommerce', 'google_sheets') then
    raise exception 'Unknown provider %', p_provider;
  end if;

  select * into v_brand from public.brands where id = p_brand_id and deleted_at is null;
  if not found then
    raise exception 'Brand not found';
  end if;
  if not public.user_has_permission(v_brand.workspace_id, 'order_ingestion.manage') then
    raise exception 'insufficient_permission: order_ingestion.manage required';
  end if;

  -- NULL param = leave unchanged (same convention as
  -- set_brand_communication_config); empty string = explicitly clear.
  insert into public.external_connections (
    workspace_id, brand_id, provider,
    shopify_shop_domain, shopify_access_token, shopify_api_secret,
    woocommerce_store_url, woocommerce_consumer_key, woocommerce_consumer_secret,
    google_spreadsheet_id, google_sheet_name, google_column_mapping, google_header_row,
    created_by, updated_by
  ) values (
    v_brand.workspace_id, p_brand_id, p_provider,
    nullif(p_shopify_shop_domain, ''), nullif(p_shopify_access_token, ''), nullif(p_shopify_api_secret, ''),
    nullif(p_woocommerce_store_url, ''), nullif(p_woocommerce_consumer_key, ''), nullif(p_woocommerce_consumer_secret, ''),
    nullif(p_google_spreadsheet_id, ''), nullif(p_google_sheet_name, ''), coalesce(p_google_column_mapping, '{}'::jsonb), coalesce(p_google_header_row, true),
    auth.uid(), auth.uid()
  )
  on conflict (brand_id, provider) do update set
    shopify_shop_domain = case when p_shopify_shop_domain is null then external_connections.shopify_shop_domain else nullif(p_shopify_shop_domain, '') end,
    shopify_access_token = case when p_shopify_access_token is null then external_connections.shopify_access_token else nullif(p_shopify_access_token, '') end,
    shopify_api_secret = case when p_shopify_api_secret is null then external_connections.shopify_api_secret else nullif(p_shopify_api_secret, '') end,
    woocommerce_store_url = case when p_woocommerce_store_url is null then external_connections.woocommerce_store_url else nullif(p_woocommerce_store_url, '') end,
    woocommerce_consumer_key = case when p_woocommerce_consumer_key is null then external_connections.woocommerce_consumer_key else nullif(p_woocommerce_consumer_key, '') end,
    woocommerce_consumer_secret = case when p_woocommerce_consumer_secret is null then external_connections.woocommerce_consumer_secret else nullif(p_woocommerce_consumer_secret, '') end,
    google_spreadsheet_id = case when p_google_spreadsheet_id is null then external_connections.google_spreadsheet_id else nullif(p_google_spreadsheet_id, '') end,
    google_sheet_name = case when p_google_sheet_name is null then external_connections.google_sheet_name else nullif(p_google_sheet_name, '') end,
    google_column_mapping = coalesce(p_google_column_mapping, external_connections.google_column_mapping),
    google_header_row = coalesce(p_google_header_row, external_connections.google_header_row),
    updated_at = now(), updated_by = auth.uid()
  returning * into v_row;

  update public.external_connections set
    status = case
      when v_row.provider = 'shopify' and v_row.shopify_shop_domain is not null and v_row.shopify_access_token is not null and v_row.shopify_api_secret is not null then 'connected'
      when v_row.provider = 'woocommerce' and v_row.woocommerce_store_url is not null and v_row.woocommerce_consumer_key is not null and v_row.woocommerce_consumer_secret is not null then 'connected'
      when v_row.provider = 'google_sheets' and v_row.google_refresh_token is not null and v_row.google_spreadsheet_id is not null then 'connected'
      else 'disconnected'
    end,
    last_error = null
    where id = v_row.id
    returning * into v_row;

  insert into public.audit_logs (workspace_id, brand_id, user_id, module, action, entity_type, entity_id, new_value)
  values (v_brand.workspace_id, p_brand_id, auth.uid(), 'order_ingestion', 'connection_saved', 'external_connections', v_row.id,
    jsonb_build_object('provider', p_provider, 'status', v_row.status));

  return v_row;
end;
$$;

comment on function public.upsert_external_connection(uuid, text, text, text, text, text, text, text, text, text, jsonb, boolean) is
  'The only write path for a brand''s Shopify/WooCommerce/Google Sheets connection config. Secret fields (access tokens, api secrets, consumer secret) are write-only — never selectable afterward except by the service-role resolvers in PART H. google_refresh_token/google_access_token are NOT settable here — those are written only by set_google_sheets_oauth_tokens() from the OAuth callback Edge Function, since a pasted access token is explicitly disallowed by design (0053''s brief: real OAuth only).';


create or replace function public.get_external_connections(p_brand_id uuid)
returns table (
  id uuid, provider text, status text, last_error text, last_sync_at timestamptz,
  shopify_shop_domain text, woocommerce_store_url text,
  google_spreadsheet_id text, google_sheet_name text, google_column_mapping jsonb, google_header_row boolean,
  google_connected boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_workspace_id uuid;
begin
  select b.workspace_id into v_workspace_id from public.brands b where b.id = p_brand_id and b.deleted_at is null;
  if not found then
    raise exception 'Brand not found';
  end if;
  if not (public.user_has_permission(v_workspace_id, 'order_ingestion.view') or public.user_has_permission(v_workspace_id, 'integrations.view')) then
    raise exception 'insufficient_permission: order_ingestion.view required';
  end if;

  return query
    select c.id, c.provider, c.status, c.last_error, c.last_sync_at,
      c.shopify_shop_domain, c.woocommerce_store_url,
      c.google_spreadsheet_id, c.google_sheet_name, c.google_column_mapping, c.google_header_row,
      (c.google_refresh_token is not null)
    from public.external_connections c
    where c.brand_id = p_brand_id;
end;
$$;

comment on function public.get_external_connections(uuid) is
  'Staff-facing connection status. Never returns a secret value — access tokens/api secrets/consumer secret/refresh token are all omitted from the result shape entirely, not merely masked.';


create or replace function public.disconnect_external_connection(p_connection_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_conn public.external_connections%rowtype;
begin
  select * into v_conn from public.external_connections where id = p_connection_id;
  if not found then
    raise exception 'Connection not found';
  end if;
  if not public.user_has_permission(v_conn.workspace_id, 'order_ingestion.manage') then
    raise exception 'insufficient_permission: order_ingestion.manage required';
  end if;

  update public.external_connections set
    status = 'disconnected',
    shopify_access_token = null, shopify_api_secret = null,
    woocommerce_consumer_key = null, woocommerce_consumer_secret = null,
    google_refresh_token = null, google_access_token = null, google_access_token_expires_at = null,
    last_error = null, updated_at = now(), updated_by = auth.uid()
  where id = p_connection_id;

  insert into public.audit_logs (workspace_id, brand_id, user_id, module, action, entity_type, entity_id, new_value)
  values (v_conn.workspace_id, v_conn.brand_id, auth.uid(), 'order_ingestion', 'connection_disconnected', 'external_connections', p_connection_id,
    jsonb_build_object('provider', v_conn.provider));
end;
$$;

comment on function public.disconnect_external_connection(uuid) is
  'Clears every secret field for a connection and marks it disconnected. Non-secret identity fields (shop domain / store URL / spreadsheet id) are kept so reconnecting doesn''t require re-typing them.';


create or replace function public.upsert_external_product_mapping(
  p_connection_id uuid,
  p_external_product_id text,
  p_external_variant_id text,
  p_external_sku text,
  p_product_id uuid
)
returns public.external_product_mappings
language plpgsql
security definer
set search_path = public
as $$
declare
  v_conn public.external_connections%rowtype;
  v_row public.external_product_mappings%rowtype;
begin
  select * into v_conn from public.external_connections where id = p_connection_id;
  if not found then
    raise exception 'Connection not found';
  end if;
  if not public.user_has_permission(v_conn.workspace_id, 'order_ingestion.manage') then
    raise exception 'insufficient_permission: order_ingestion.manage required';
  end if;
  if not exists (select 1 from public.products where id = p_product_id and brand_id = v_conn.brand_id and deleted_at is null) then
    raise exception 'Product not found in this brand';
  end if;

  insert into public.external_product_mappings (
    workspace_id, brand_id, connection_id, external_product_id, external_variant_id, external_sku, product_id, created_by
  ) values (
    v_conn.workspace_id, v_conn.brand_id, p_connection_id,
    nullif(p_external_product_id, ''), nullif(p_external_variant_id, ''), nullif(p_external_sku, ''), p_product_id, auth.uid()
  )
  on conflict (connection_id, external_product_id, external_variant_id) do update set
    external_sku = excluded.external_sku, product_id = excluded.product_id, updated_at = now()
  returning * into v_row;

  return v_row;
end;
$$;

comment on function public.upsert_external_product_mapping(uuid, text, text, text, uuid) is
  'Staff-facing product-mapping editor, typically used from the Failed Order Review screen against an item in a needs_review row''s unresolved_items. Does not itself retry the ingestion — call retry_external_order_ingestion() afterward.';


create or replace function public.retry_external_order_ingestion(p_log_id uuid)
returns public.external_order_ingestion_log
language plpgsql
security definer
set search_path = public
as $$
declare
  v_log public.external_order_ingestion_log%rowtype;
begin
  select * into v_log from public.external_order_ingestion_log where id = p_log_id;
  if not found then
    raise exception 'Ingestion log row not found';
  end if;
  if not public.user_has_permission(v_log.workspace_id, 'order_ingestion.manage') then
    raise exception 'insufficient_permission: order_ingestion.manage required';
  end if;
  if v_log.status not in ('needs_review', 'failed', 'permanently_failed') then
    raise exception 'Only a needs_review, failed, or permanently_failed row can be retried (current status: %)', v_log.status;
  end if;

  update public.external_order_ingestion_log
    set status = 'pending', attempts = 0, next_retry_at = null, error_message = null, updated_at = now()
    where id = p_log_id;

  insert into public.audit_logs (workspace_id, brand_id, user_id, module, action, entity_type, entity_id, new_value)
  values (v_log.workspace_id, v_log.brand_id, auth.uid(), 'order_ingestion', 'manual_retry', 'external_order_ingestion_log', p_log_id,
    jsonb_build_object('provider', v_log.provider, 'external_order_id', v_log.external_order_id));

  return public.process_external_order_ingestion(p_log_id);
end;
$$;

comment on function public.retry_external_order_ingestion(uuid) is
  'Manual, permission-gated retry: resets attempts to 0 (a fresh backoff budget) and reprocesses immediately, using the row''s own stored input_customer/input_items — never re-fetches from the provider. The correct action after fixing a product mapping on a needs_review row, or forcing an early retry of a failed/permanently_failed one.';


create or replace function public.list_external_ingestion_log(
  p_workspace_id uuid,
  p_status text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns setof public.external_order_ingestion_log
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not (public.user_has_permission(p_workspace_id, 'order_ingestion.view') or public.user_has_permission(p_workspace_id, 'integrations.view')) then
    raise exception 'insufficient_permission: order_ingestion.view required';
  end if;
  return query
    select * from public.external_order_ingestion_log
    where workspace_id = p_workspace_id and (p_status is null or status = p_status)
    order by created_at desc
    limit p_limit offset p_offset;
end;
$$;


create or replace function public.get_external_ingestion_health(p_workspace_id uuid)
returns table (
  pending bigint, processing bigint, needs_review bigint, failed bigint, permanently_failed bigint,
  ingested_recent bigint, oldest_pending_at timestamptz, last_success_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not (public.user_has_permission(p_workspace_id, 'order_ingestion.view') or public.user_has_permission(p_workspace_id, 'integrations.view')) then
    raise exception 'insufficient_permission: order_ingestion.view required';
  end if;
  return query
    select
      count(*) filter (where status = 'pending'),
      count(*) filter (where status = 'processing'),
      count(*) filter (where status = 'needs_review'),
      count(*) filter (where status = 'failed'),
      count(*) filter (where status = 'permanently_failed'),
      count(*) filter (where status = 'ingested' and updated_at > now() - interval '24 hours'),
      min(created_at) filter (where status = 'pending'),
      max(updated_at) filter (where status = 'ingested')
    from public.external_order_ingestion_log
    where workspace_id = p_workspace_id;
end;
$$;

comment on function public.get_external_ingestion_health(uuid) is
  'Rollup for the Integration Health Center''s Order Sources card — same shape/intent as get_queue_health() (0035), scoped to this one queue.';


-- ================================================================
-- PART H — service-role-only RPCs for the ingestion Edge Functions.
-- All revoked from public/anon/authenticated; callable only via the
-- Supabase service_role key, exactly like claim_communication_log_batch.
-- ================================================================
create or replace function public.get_external_connection_for_dispatch(p_connection_id uuid)
returns public.external_connections
language sql
stable
security definer
set search_path = public
as $$
  select * from public.external_connections where id = p_connection_id;
$$;

revoke execute on function public.get_external_connection_for_dispatch(uuid) from public, anon, authenticated;

comment on function public.get_external_connection_for_dispatch(uuid) is
  'Returns the FULL row including secrets — safe only because EXECUTE is revoked from every client role. Used by the Shopify webhook receiver (resolve by shop domain first, then this) and by the WooCommerce/Google Sheets sync workers to fetch credentials for one connection.';


create or replace function public.get_shopify_connection_by_domain(p_shop_domain text)
returns public.external_connections
language sql
stable
security definer
set search_path = public
as $$
  select * from public.external_connections
  where provider = 'shopify' and shopify_shop_domain = p_shop_domain and status = 'connected'
  limit 1;
$$;

revoke execute on function public.get_shopify_connection_by_domain(text) from public, anon, authenticated;

comment on function public.get_shopify_connection_by_domain(text) is
  'Resolves an inbound Shopify webhook''s X-Shopify-Shop-Domain header to a connection BEFORE the HMAC signature is verified — the api_secret needed to verify the signature has to come from somewhere, and this is the only lookup key Shopify gives a webhook receiver.';


create or replace function public.list_active_external_connections(p_provider text)
returns setof public.external_connections
language sql
stable
security definer
set search_path = public
as $$
  select * from public.external_connections where provider = p_provider and status = 'connected';
$$;

revoke execute on function public.list_active_external_connections(text) from public, anon, authenticated;

comment on function public.list_active_external_connections(text) is
  'Used by the WooCommerce and Google Sheets sync worker Edge Functions to enumerate every connected store/spreadsheet to poll on each scheduled run — the pull-based equivalent of Shopify''s push webhook.';


create or replace function public.update_external_connection_sync_cursor(
  p_connection_id uuid,
  p_cursor jsonb,
  p_status text default 'connected',
  p_error text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_status not in ('connected', 'error') then
    raise exception 'Unknown status %', p_status;
  end if;
  update public.external_connections
    set sync_cursor = coalesce(p_cursor, sync_cursor), last_sync_at = now(), status = p_status, last_error = p_error, updated_at = now()
    where id = p_connection_id;
end;
$$;

revoke execute on function public.update_external_connection_sync_cursor(uuid, jsonb, text, text) from public, anon, authenticated;

comment on function public.update_external_connection_sync_cursor(uuid, jsonb, text, text) is
  'Called once per sync-worker run (WooCommerce/Google Sheets) after every order in the batch has already gone through ingest_external_order() individually. Advancing the cursor only after the whole batch succeeds means a worker crash mid-batch simply re-fetches the same page next run — safe, since ingest_external_order() is idempotent per order.';


create or replace function public.set_google_sheets_oauth_tokens(
  p_connection_id uuid,
  p_refresh_token text,
  p_access_token text,
  p_expires_at timestamptz
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.external_connections
    set google_refresh_token = coalesce(nullif(p_refresh_token, ''), google_refresh_token),
        google_access_token = p_access_token,
        google_access_token_expires_at = p_expires_at,
        status = case when google_spreadsheet_id is not null and coalesce(nullif(p_refresh_token, ''), google_refresh_token) is not null then 'connected' else status end,
        last_error = null,
        updated_at = now()
    where id = p_connection_id and provider = 'google_sheets';
end;
$$;

revoke execute on function public.set_google_sheets_oauth_tokens(uuid, text, text, timestamptz) from public, anon, authenticated;

comment on function public.set_google_sheets_oauth_tokens(uuid, text, text, timestamptz) is
  'Written only by the google-oauth-callback Edge Function immediately after exchanging an authorization code with Google — this is what makes the flow real OAuth rather than a pasted access token: the refresh_token never passes through the browser or a form field.';


create or replace function public.claim_external_ingestion_retry_batch(p_worker_id text, p_limit integer default 20)
returns setof uuid
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with claimed as (
    select l.id from public.external_order_ingestion_log l
    where (l.status = 'failed' and l.next_retry_at <= now())
       or (l.status = 'processing' and l.claimed_at < now() - interval '10 minutes')
    order by l.created_at
    limit p_limit
    for update skip locked
  ),
  updated as (
    update public.external_order_ingestion_log l
      set claimed_at = now(), claimed_by = p_worker_id, updated_at = now()
      from claimed
      where l.id = claimed.id
      returning l.id
  )
  select id from updated;
end;
$$;

revoke execute on function public.claim_external_ingestion_retry_batch(text, integer) from public, anon, authenticated;

comment on function public.claim_external_ingestion_retry_batch(text, integer) is
  'Same FOR UPDATE SKIP LOCKED claim pattern as claim_communication_log_batch/claim_tracking_dispatch_batch (0032) — concurrent retry-worker invocations can never double-process the same failed row. The retry-external-ingestion Edge Function calls this, then process_external_order_ingestion() for each returned id.';


-- ----------------------------------------------------------------
-- PART I — realtime, so the Integration Health Center''s Order
-- Sources section updates live exactly like every other queue card
-- (0032/0035). Guarded the same way as every other publication add —
-- a safe no-op on a plain local Postgres with no supabase_realtime
-- publication.
-- ----------------------------------------------------------------
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    execute 'alter publication supabase_realtime add table public.external_order_ingestion_log';
    execute 'alter publication supabase_realtime add table public.external_connections';
  end if;
end $$;
